In [2]:
import torch
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'None'}")

CUDA available: True
GPU: NVIDIA A100-SXM4-80GB

In [3]:
!pip install -q datasets transformers accelerate huggingface-hub wandb bitsandbytes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.4/59.4 MB 40.9 MB/s eta 0:00:00

In [4]:
from huggingface_hub import login
import wandb

# Get your token from https://huggingface.co/settings/tokens
login(token="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")

# wandb logging
run = wandb.init(
    project="nl2sh",
    name="run01",
)

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: dchan35 (dchan35-university-of-illinois-chicago) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [5]:
# Models to fine-tune
MODELS_TO_FINETUNE = [
    {
        "model_id": "meta-llama/Llama-3.2-1B-Instruct",
        "output_name": "llama_1b_nl2sh_finetuned",
        "is_llama": True,
        "batch_size": 8,  # Adjusted for T4
    },
    {
        "model_id": "Qwen/Qwen2.5-Coder-0.5B-Instruct",
        "output_name": "qwen_0.5b_nl2sh_finetuned",
        "is_llama": False,
        "batch_size": 12,  # Smaller model, larger batch
    }
]

print("Configuration loaded!")

Configuration loaded!

In [6]:
import gc
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments

def finetune_model(config):
    """Fine-tune on FULL dataset with A100"""

    model_id = config["model_id"]
    output_name = config["output_name"]
    is_llama = config["is_llama"]

    print("\n" + "="*80)
    print(f"FINE-TUNING: {model_id}")
    print("="*80 + "\n")

    # Initialize WandB
    run = wandb.init(
        project="nl2sh",
        name=output_name,
        reinit=True
    )

    # Load model
    print(f"Loading {model_id}...")
    tokenizer = AutoTokenizer.from_pretrained(
        model_id,
        clean_up_tokenization_spaces=False
    )

    # Use bfloat16 on A100
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        device_map="auto",
        torch_dtype=torch.bfloat16,  # A100 supports this!
        low_cpu_mem_usage=True
    )

    # Set pad token for Llama
    if is_llama:
        tokenizer.pad_token = '<|finetune_right_pad_id|>'
        print("Set pad_token for Llama model")

    print(f"Model loaded with {model.num_parameters():,} parameters")

    # Dataset functions
    def apply_chat_template(row):
        messages = [
            {
                "role": "system",
                "content": "Your task is to translate a natural language instruction to a Bash command. You will receive an instruction in English and output a Bash command that can be run in a Linux terminal."
            },
            {"role": "user", "content": row['nl']},
            {"role": "assistant", "content": row['bash']}
        ]
        prompt = tokenizer.apply_chat_template(
            messages,
            add_generation_prompt=False,
            tokenize=False,
        )
        return {"prompt": prompt}

    def tokenize_rows(row):
        tokens = tokenizer(
            row['prompt'],
            padding="max_length",
            truncation=True,
            max_length=150
        )
        tokens['labels'] = [
            -100 if token == tokenizer.pad_token_id else token
            for token in tokens['input_ids']
        ]
        return tokens

    # Load FULL datasets
    print("Loading FULL datasets...")
    train_dataset = load_dataset("westenfelder/NL2SH-ALFA", "train", split="train")  # All 40k
    test_dataset = load_dataset("westenfelder/NL2SH-ALFA", "test", split="train")    # All 600

    print(f"Train: {len(train_dataset)}, Test: {len(test_dataset)}")

    # Format and tokenize
    print("Formatting datasets...")
    formatted_train_dataset = train_dataset.map(apply_chat_template)
    formatted_test_dataset = test_dataset.map(apply_chat_template)

    print("Tokenizing datasets...")
    tokenized_train_dataset = formatted_train_dataset.map(tokenize_rows)
    tokenized_test_dataset = formatted_test_dataset.map(tokenize_rows)

    final_train_dataset = tokenized_train_dataset.remove_columns(['nl', 'bash', 'prompt'])
    final_test_dataset = tokenized_test_dataset.remove_columns(['nl', 'bash', 'prompt'])

    print("Dataset prepared!")

    # Training configuration - Paper's original settings
    model.train()

    training_args = TrainingArguments(
        output_dir=f"checkpoints/{output_name}",
        eval_strategy="steps",
        eval_steps=1000,
        logging_steps=100,
        save_steps=5000,
        per_device_train_batch_size=15,  # Paper's settings
        per_device_eval_batch_size=15,
        gradient_accumulation_steps=5,
        num_train_epochs=10,  # Paper's settings
        report_to="wandb",
        log_level="info",
        learning_rate=1e-5,
        max_grad_norm=2,
        weight_decay=0.01,
        seed=123,
        bf16=True,  # A100 supports this!
        save_total_limit=2,
    )

    # Initialize trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=final_train_dataset,
        eval_dataset=final_test_dataset,
        tokenizer=tokenizer
    )

    # Train
    print("\n🚀 Starting training...")
    trainer.train(resume_from_checkpoint=False)

    # Save
    print(f"\n💾 Saving to {output_name}/")
    trainer.save_model(output_name)
    tokenizer.save_pretrained(output_name)

    wandb.finish()

    print(f"✅ Fine-tuning complete: {model_id}")

    # Clean up
    del model, tokenizer, trainer
    gc.collect()
    torch.cuda.empty_cache()

    return output_name

In [7]:
import time

start_time = time.time()
finetuned_models = []

for i, config in enumerate(MODELS_TO_FINETUNE, 1):
    print(f"\n{'#'*80}")
    print(f"# MODEL {i}/{len(MODELS_TO_FINETUNE)}")
    print(f"{'#'*80}\n")

    try:
        output_path = finetune_model(config)
        finetuned_models.append(output_path)
        print(f"\n✅ Completed {i}/{len(MODELS_TO_FINETUNE)} models")
    except Exception as e:
        print(f"\n❌ Error with {config['model_id']}: {e}")
        continue

total_time = time.time() - start_time

print(f"\n{'='*80}")
print(f"🎉 TRAINING COMPLETE!")
print(f"⏱️  Total time: {total_time/3600:.2f} hours")
print(f"📁 Models saved: {finetuned_models}")
print(f"{'='*80}")

################################################################################
# MODEL 1/2
################################################################################


================================================================================
FINE-TUNING: meta-llama/Llama-3.2-1B-Instruct
================================================================================

wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.

Loading meta-llama/Llama-3.2-1B-Instruct...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/54.5k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/877 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/2.47G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

Set pad_token for Llama model
Model loaded with 1,235,814,400 parameters
Loading FULL datasets...

README.md: 0.00B [00:00, ?B/s]

train.csv: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/40639 [00:00<?, ? examples/s]

test.csv: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/300 [00:00<?, ? examples/s]

Train: 40639, Test: 300
Formatting datasets...

Map:   0%|          | 0/40639 [00:00<?, ? examples/s]

Map:   0%|          | 0/300 [00:00<?, ? examples/s]

Tokenizing datasets...

Map:   0%|          | 0/40639 [00:00<?, ? examples/s]

Map:   0%|          | 0/300 [00:00<?, ? examples/s]

/tmp/ipython-input-3860937.py:120: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
The model is already on multiple devices. Skipping the move to device specified in `args`.
Using auto half precision backend
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 128009, 'pad_token_id': 128004}.

Dataset prepared!

🚀 Starting training...

***** Running training *****
  Num examples = 40,639
  Num Epochs = 10
  Instantaneous batch size per device = 15
  Total train batch size (w. parallel, distributed & accumulation) = 75
  Gradient Accumulation steps = 5
  Total optimization steps = 5,420
  Number of trainable parameters = 1,235,814,400
Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"

The following columns in the Evaluation set don't have a corresponding argument in `LlamaForCausalLM.forward` and have been ignored: difficulty, bash2. If difficulty, bash2 are not expected by `LlamaForCausalLM.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 300
  Batch size = 15
The following columns in the Evaluation set don't have a corresponding argument in `LlamaForCausalLM.forward` and have been ignored: difficulty, bash2. If difficulty, bash2 are not expected by `LlamaForCausalLM.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 300
  Batch size = 15
The following columns in the Evaluation set don't have a corresponding argument in `LlamaForCausalLM.forward` and have been ignored: difficulty, bash2. If difficulty, bash2 are not expected by `LlamaForCausalLM.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 300
  Batch size = 15
The following columns in the Evaluation set don't have a corresponding argument in `LlamaForCausalLM.forward` and have been ignored: difficulty, bash2. If difficulty, bash2 are not expected by `LlamaForCausalLM.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 300
  Batch size = 15
The following columns in the Evaluation set don't have a corresponding argument in `LlamaForCausalLM.forward` and have been ignored: difficulty, bash2. If difficulty, bash2 are not expected by `LlamaForCausalLM.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 300
  Batch size = 15
Saving model checkpoint to checkpoints/llama_1b_nl2sh_finetuned/checkpoint-5000
Configuration saved in checkpoints/llama_1b_nl2sh_finetuned/checkpoint-5000/config.json
Configuration saved in checkpoints/llama_1b_nl2sh_finetuned/checkpoint-5000/generation_config.json
Model weights saved in checkpoints/llama_1b_nl2sh_finetuned/checkpoint-5000/model.safetensors
chat template saved in checkpoints/llama_1b_nl2sh_finetuned/checkpoint-5000/chat_template.jinja
tokenizer config file saved in checkpoints/llama_1b_nl2sh_finetuned/checkpoint-5000/tokenizer_config.json
Special tokens file saved in checkpoints/llama_1b_nl2sh_finetuned/checkpoint-5000/special_tokens_map.json
Saving model checkpoint to checkpoints/llama_1b_nl2sh_finetuned/checkpoint-5420
Configuration saved in checkpoints/llama_1b_nl2sh_finetuned/checkpoint-5420/config.json
Configuration saved in checkpoints/llama_1b_nl2sh_finetuned/checkpoint-5420/generation_config.json
Model weights saved in checkpoints/llama_1b_nl2sh_finetuned/checkpoint-5420/model.safetensors
chat template saved in checkpoints/llama_1b_nl2sh_finetuned/checkpoint-5420/chat_template.jinja
tokenizer config file saved in checkpoints/llama_1b_nl2sh_finetuned/checkpoint-5420/tokenizer_config.json
Special tokens file saved in checkpoints/llama_1b_nl2sh_finetuned/checkpoint-5420/special_tokens_map.json


Training completed. Do not forget to share your model on huggingface.co/models =)


Saving model checkpoint to llama_1b_nl2sh_finetuned
Configuration saved in llama_1b_nl2sh_finetuned/config.json
Configuration saved in llama_1b_nl2sh_finetuned/generation_config.json

💾 Saving to llama_1b_nl2sh_finetuned/

Model weights saved in llama_1b_nl2sh_finetuned/model.safetensors
chat template saved in llama_1b_nl2sh_finetuned/chat_template.jinja
tokenizer config file saved in llama_1b_nl2sh_finetuned/tokenizer_config.json
Special tokens file saved in llama_1b_nl2sh_finetuned/special_tokens_map.json
chat template saved in llama_1b_nl2sh_finetuned/chat_template.jinja
tokenizer config file saved in llama_1b_nl2sh_finetuned/tokenizer_config.json
Special tokens file saved in llama_1b_nl2sh_finetuned/special_tokens_map.json

✅ Fine-tuning complete: meta-llama/Llama-3.2-1B-Instruct

✅ Completed 1/2 models

################################################################################
# MODEL 2/2
################################################################################


================================================================================
FINE-TUNING: Qwen/Qwen2.5-Coder-0.5B-Instruct
================================================================================

Loading Qwen/Qwen2.5-Coder-0.5B-Instruct...

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

loading file vocab.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-Coder-0.5B-Instruct/snapshots/ea3f2471cf1b1f0db85067f1ef93848e38e88c25/vocab.json
loading file merges.txt from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-Coder-0.5B-Instruct/snapshots/ea3f2471cf1b1f0db85067f1ef93848e38e88c25/merges.txt
loading file tokenizer.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-Coder-0.5B-Instruct/snapshots/ea3f2471cf1b1f0db85067f1ef93848e38e88c25/tokenizer.json
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at None
loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-Coder-0.5B-Instruct/snapshots/ea3f2471cf1b1f0db85067f1ef93848e38e88c25/tokenizer_config.json
loading file chat_template.jinja from cache at None
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-Coder-0.5B-Instruct/snapshots/ea3f2471cf1b1f0db85067f1ef93848e38e88c25/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 24,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "4.57.1",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

model.safetensors:   0%|          | 0.00/988M [00:00<?, ?B/s]

loading weights file model.safetensors from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-Coder-0.5B-Instruct/snapshots/ea3f2471cf1b1f0db85067f1ef93848e38e88c25/model.safetensors
Instantiating Qwen2ForCausalLM model under default dtype torch.bfloat16.
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151645
}

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

loading configuration file generation_config.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-Coder-0.5B-Instruct/snapshots/ea3f2471cf1b1f0db85067f1ef93848e38e88c25/generation_config.json
Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.05,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

Could not locate the custom_generate/generate.py inside Qwen/Qwen2.5-Coder-0.5B-Instruct.

Model loaded with 494,032,768 parameters
Loading FULL datasets...
Train: 40639, Test: 300
Formatting datasets...

Map:   0%|          | 0/40639 [00:00<?, ? examples/s]

Map:   0%|          | 0/300 [00:00<?, ? examples/s]

Tokenizing datasets...

Map:   0%|          | 0/40639 [00:00<?, ? examples/s]

Map:   0%|          | 0/300 [00:00<?, ? examples/s]

PyTorch: setting up devices
/tmp/ipython-input-3860937.py:120: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
The model is already on multiple devices. Skipping the move to device specified in `args`.
Using auto half precision backend
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

Dataset prepared!

🚀 Starting training...

***** Running training *****
  Num examples = 40,639
  Num Epochs = 10
  Instantaneous batch size per device = 15
  Total train batch size (w. parallel, distributed & accumulation) = 75
  Gradient Accumulation steps = 5
  Total optimization steps = 5,420
  Number of trainable parameters = 494,032,768
Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"

The following columns in the Evaluation set don't have a corresponding argument in `Qwen2ForCausalLM.forward` and have been ignored: difficulty, bash2. If difficulty, bash2 are not expected by `Qwen2ForCausalLM.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 300
  Batch size = 15
The following columns in the Evaluation set don't have a corresponding argument in `Qwen2ForCausalLM.forward` and have been ignored: difficulty, bash2. If difficulty, bash2 are not expected by `Qwen2ForCausalLM.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 300
  Batch size = 15
The following columns in the Evaluation set don't have a corresponding argument in `Qwen2ForCausalLM.forward` and have been ignored: difficulty, bash2. If difficulty, bash2 are not expected by `Qwen2ForCausalLM.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 300
  Batch size = 15
The following columns in the Evaluation set don't have a corresponding argument in `Qwen2ForCausalLM.forward` and have been ignored: difficulty, bash2. If difficulty, bash2 are not expected by `Qwen2ForCausalLM.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 300
  Batch size = 15

The following columns in the Evaluation set don't have a corresponding argument in `Qwen2ForCausalLM.forward` and have been ignored: difficulty, bash2. If difficulty, bash2 are not expected by `Qwen2ForCausalLM.forward`,  you can safely ignore this message.

***** Running Evaluation *****
  Num examples = 300
  Batch size = 15
Saving model checkpoint to checkpoints/qwen_0.5b_nl2sh_finetuned/checkpoint-5000
Configuration saved in checkpoints/qwen_0.5b_nl2sh_finetuned/checkpoint-5000/config.json
Configuration saved in checkpoints/qwen_0.5b_nl2sh_finetuned/checkpoint-5000/generation_config.json
Model weights saved in checkpoints/qwen_0.5b_nl2sh_finetuned/checkpoint-5000/model.safetensors
chat template saved in checkpoints/qwen_0.5b_nl2sh_finetuned/checkpoint-5000/chat_template.jinja
tokenizer config file saved in checkpoints/qwen_0.5b_nl2sh_finetuned/checkpoint-5000/tokenizer_config.json
Special tokens file saved in checkpoints/qwen_0.5b_nl2sh_finetuned/checkpoint-5000/special_tokens_map.json
Saving model checkpoint to checkpoints/qwen_0.5b_nl2sh_finetuned/checkpoint-5420
Configuration saved in checkpoints/qwen_0.5b_nl2sh_finetuned/checkpoint-5420/config.json
Configuration saved in checkpoints/qwen_0.5b_nl2sh_finetuned/checkpoint-5420/generation_config.json
Model weights saved in checkpoints/qwen_0.5b_nl2sh_finetuned/checkpoint-5420/model.safetensors
chat template saved in checkpoints/qwen_0.5b_nl2sh_finetuned/checkpoint-5420/chat_template.jinja
tokenizer config file saved in checkpoints/qwen_0.5b_nl2sh_finetuned/checkpoint-5420/tokenizer_config.json
Special tokens file saved in checkpoints/qwen_0.5b_nl2sh_finetuned/checkpoint-5420/special_tokens_map.json


Training completed. Do not forget to share your model on huggingface.co/models =)


Saving model checkpoint to qwen_0.5b_nl2sh_finetuned
Configuration saved in qwen_0.5b_nl2sh_finetuned/config.json
Configuration saved in qwen_0.5b_nl2sh_finetuned/generation_config.json

💾 Saving to qwen_0.5b_nl2sh_finetuned/

Model weights saved in qwen_0.5b_nl2sh_finetuned/model.safetensors
chat template saved in qwen_0.5b_nl2sh_finetuned/chat_template.jinja
tokenizer config file saved in qwen_0.5b_nl2sh_finetuned/tokenizer_config.json
Special tokens file saved in qwen_0.5b_nl2sh_finetuned/special_tokens_map.json
chat template saved in qwen_0.5b_nl2sh_finetuned/chat_template.jinja
tokenizer config file saved in qwen_0.5b_nl2sh_finetuned/tokenizer_config.json
Special tokens file saved in qwen_0.5b_nl2sh_finetuned/special_tokens_map.json

✅ Fine-tuning complete: Qwen/Qwen2.5-Coder-0.5B-Instruct

✅ Completed 2/2 models

================================================================================
🎉 TRAINING COMPLETE!
⏱️  Total time: 2.09 hours
📁 Models saved: ['llama_1b_nl2sh_finetuned', 'qwen_0.5b_nl2sh_finetuned']
================================================================================

In [8]:
from transformers import pipeline

test_prompts = [
    "list all files in current directory",
    "find all python files",
    "count lines in a text file",
    "remove all .tmp files",
    "show disk usage"
]

print("\n" + "="*80)
print("TESTING FINE-TUNED MODELS")
print("="*80)

for model_path in finetuned_models:
    print(f"\n{'─'*80}")
    print(f"Model: {model_path}")
    print(f"{'─'*80}\n")

    tokenizer = AutoTokenizer.from_pretrained(model_path)
    generator = pipeline(
        "text-generation",
        model=model_path,
        tokenizer=model_path,
        device=0 if torch.cuda.is_available() else -1
    )

    system_msg = "Your task is to translate a natural language instruction to a Bash command."

    for prompt in test_prompts:
        messages = [
            {"role": "system", "content": system_msg},
            {"role": "user", "content": prompt}
        ]

        formatted = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )

        output = generator(formatted, max_new_tokens=50, do_sample=False)
        result = output[0]['generated_text']

        # Extract just the assistant's response
        if "assistant" in result:
            result = result.split("assistant")[-1].strip()

        print(f"📝 {prompt}")
        print(f"💻 {result[:100]}")  # First 100 chars
        print()

loading file tokenizer.json
loading file tokenizer.model
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file chat_template.jinja

================================================================================
TESTING FINE-TUNED MODELS
================================================================================

────────────────────────────────────────────────────────────────────────────────
Model: llama_1b_nl2sh_finetuned
────────────────────────────────────────────────────────────────────────────────

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
loading configuration file llama_1b_nl2sh_finetuned/config.json
Model config LlamaConfig {
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 128000,
  "dtype": "bfloat16",
  "eos_token_id": 128009,
  "head_dim": 64,
  "hidden_act": "silu",
  "hidden_size": 2048,
  "initializer_range": 0.02,
  "intermediate_size": 8192,
  "max_position_embeddings": 131072,
  "mlp_bias": false,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 16,
  "num_key_value_heads": 8,
  "pad_token_id": 128004,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": {
    "factor": 32.0,
    "high_freq_factor": 4.0,
    "low_freq_factor": 1.0,
    "original_max_position_embeddings": 8192,
    "rope_type": "llama3"
  },
  "rope_theta": 500000.0,
  "tie_word_embeddings": true,
  "transformers_version": "4.57.1",
  "use_cache": true,
  "vocab_size": 128256
}

loading configuration file llama_1b_nl2sh_finetuned/config.json
Model config LlamaConfig {
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 128000,
  "dtype": "bfloat16",
  "eos_token_id": 128009,
  "head_dim": 64,
  "hidden_act": "silu",
  "hidden_size": 2048,
  "initializer_range": 0.02,
  "intermediate_size": 8192,
  "max_position_embeddings": 131072,
  "mlp_bias": false,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 16,
  "num_key_value_heads": 8,
  "pad_token_id": 128004,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": {
    "factor": 32.0,
    "high_freq_factor": 4.0,
    "low_freq_factor": 1.0,
    "original_max_position_embeddings": 8192,
    "rope_type": "llama3"
  },
  "rope_theta": 500000.0,
  "tie_word_embeddings": true,
  "transformers_version": "4.57.1",
  "use_cache": true,
  "vocab_size": 128256
}

loading weights file llama_1b_nl2sh_finetuned/model.safetensors
Will use dtype=torch.bfloat16 as defined in model's config object
Instantiating LlamaForCausalLM model under default dtype torch.bfloat16.
Generate config GenerationConfig {
  "bos_token_id": 128000,
  "eos_token_id": 128009,
  "pad_token_id": 128004
}

loading configuration file llama_1b_nl2sh_finetuned/generation_config.json
Generate config GenerationConfig {
  "bos_token_id": 128000,
  "do_sample": true,
  "eos_token_id": [
    128009,
    128001,
    128008,
    128009
  ],
  "pad_token_id": 128004,
  "temperature": 0.6,
  "top_p": 0.9
}

Could not locate the custom_generate/generate.py inside llama_1b_nl2sh_finetuned.
loading file tokenizer.json
loading file tokenizer.model
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file chat_template.jinja
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Device set to use cuda:0
The following generation flags are not valid and may be ignored: ['temperature', 'top_p'].
- `temperature`: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
- `top_p`: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
If you're using a pretrained model, note that some of these attributes may be set through the model's `generation_config.json` file.

📝 list all files in current directory
💻 <|end_header_id|>

find. -type f

📝 find all python files
💻 <|end_header_id|>

find. -name "*.py"

📝 count lines in a text file
💻 <|end_header_id|>

cat path/to/file.txt | wc -l

loading file vocab.json
loading file merges.txt
loading file tokenizer.json
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file chat_template.jinja

📝 remove all .tmp files
💻 <|end_header_id|>

find. -name "*.tmp" -delete

📝 show disk usage
💻 <|end_header_id|>

sudo du -sh /


────────────────────────────────────────────────────────────────────────────────
Model: qwen_0.5b_nl2sh_finetuned
────────────────────────────────────────────────────────────────────────────────

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
loading configuration file qwen_0.5b_nl2sh_finetuned/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 24,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": 151643,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "4.57.1",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

loading configuration file qwen_0.5b_nl2sh_finetuned/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 24,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": 151643,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "4.57.1",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

loading weights file qwen_0.5b_nl2sh_finetuned/model.safetensors
Will use dtype=torch.bfloat16 as defined in model's config object
Instantiating Qwen2ForCausalLM model under default dtype torch.bfloat16.
Generate config GenerationConfig {
  "eos_token_id": 151645,
  "pad_token_id": 151643
}

loading configuration file qwen_0.5b_nl2sh_finetuned/generation_config.json
Generate config GenerationConfig {
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.05,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

Could not locate the custom_generate/generate.py inside qwen_0.5b_nl2sh_finetuned.
loading file vocab.json
loading file merges.txt
loading file tokenizer.json
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file chat_template.jinja
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Device set to use cuda:0
The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k'].
- `temperature`: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
- `top_p`: `do_sample` is set to `False`. However, `top_p` is set to `0.8` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
- `top_k`: `do_sample` is set to `False`. However, `top_k` is set to `20` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_k`.
If you're using a pretrained model, note that some of these attributes may be set through the model's `generation_config.json` file.

📝 list all files in current directory
💻 find. -type f -print

📝 find all python files
💻 find. -name "*.py"

📝 count lines in a text file
💻 wc -l path/to/file

📝 remove all .tmp files
💻 find. -name "*.tmp" -exec rm {} \;

📝 show disk usage
💻 du -h /

In [9]:
import shutil
from google.colab import files

print("\n📦 Preparing models for download...\n")

for model_path in finetuned_models:
    print(f"Zipping {model_path}...")
    shutil.make_archive(model_path, 'zip', model_path)
    print(f"✅ Created {model_path}.zip")

# Download
for model_path in finetuned_models:
    print(f"\n⬇️  Downloading {model_path}.zip...")
    files.download(f"{model_path}.zip")

print("\n✅ All downloads complete!")

📦 Preparing models for download...

Zipping llama_1b_nl2sh_finetuned...
✅ Created llama_1b_nl2sh_finetuned.zip
Zipping qwen_0.5b_nl2sh_finetuned...
✅ Created qwen_0.5b_nl2sh_finetuned.zip

⬇️  Downloading llama_1b_nl2sh_finetuned.zip...

⬇️  Downloading qwen_0.5b_nl2sh_finetuned.zip...

✅ All downloads complete!

In [10]:
# ========================================
# BENCHMARKING ON TEST SET
# ========================================

from datasets import load_dataset
from tqdm import tqdm
import csv

print("\n" + "="*80)
print("BENCHMARKING ON NL2SH-ALFA TEST SET (600 EXAMPLES)")
print("="*80 + "\n")

# Load test dataset
test_dataset = load_dataset("westenfelder/NL2SH-ALFA", "test", split="train")
print(f"Loaded {len(test_dataset)} test examples\n")

system_prompt = "Your task is to translate a natural language instruction to a Bash command. You will receive an instruction in English and output a Bash command that can be run in a Linux terminal."

# Benchmark each model
for model_path in ['llama_1b_nl2sh_finetuned', 'qwen_0.5b_nl2sh_finetuned']:
    print(f"{'='*80}")
    print(f"Evaluating: {model_path}")
    print(f"{'='*80}\n")

    # Load model
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        device_map="auto",
        torch_dtype=torch.bfloat16
    )

    results = []
    correct = 0

    for example in tqdm(test_dataset, desc="Generating predictions"):
        prompt = example['nl']
        ground_truth = example['bash']

        # Format
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": prompt}
        ]

        formatted = tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )

        # Generate
        inputs = tokenizer(formatted, return_tensors="pt").to(model.device)
        outputs = model.generate(
            **inputs,
            max_new_tokens=100,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

        # Decode
        response = outputs[0][inputs.input_ids.shape[-1]:]
        prediction = tokenizer.decode(response, skip_special_tokens=True).strip()

        # Check exact match
        is_correct = (prediction == ground_truth)
        if is_correct:
            correct += 1

        results.append({
            "prompt": prompt,
            "ground_truth": ground_truth,
            "prediction": prediction,
            "correct": 1 if is_correct else 0
        })

    # Calculate accuracy
    accuracy = (correct / len(test_dataset)) * 100

    print(f"\n{'─'*80}")
    print(f"📊 RESULTS: {model_path}")
    print(f"{'─'*80}")
    print(f"Correct: {correct}/{len(test_dataset)}")
    print(f"Accuracy: {accuracy:.2f}%")
    print(f"{'─'*80}\n")

    # Save to CSV
    csv_filename = f"{model_path}_benchmark.csv"
    with open(csv_filename, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=['prompt', 'ground_truth', 'prediction', 'correct'])
        writer.writeheader()
        writer.writerows(results)
    print(f"✅ Saved results to {csv_filename}\n")

    # Clean up
    del model, tokenizer
    torch.cuda.empty_cache()

print("\n🎉 BENCHMARKING COMPLETE!")

================================================================================
BENCHMARKING ON NL2SH-ALFA TEST SET (600 EXAMPLES)
================================================================================

loading file tokenizer.json
loading file tokenizer.model
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file chat_template.jinja

Loaded 300 test examples

================================================================================
Evaluating: llama_1b_nl2sh_finetuned
================================================================================

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
loading configuration file llama_1b_nl2sh_finetuned/config.json
Model config LlamaConfig {
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 128000,
  "dtype": "bfloat16",
  "eos_token_id": 128009,
  "head_dim": 64,
  "hidden_act": "silu",
  "hidden_size": 2048,
  "initializer_range": 0.02,
  "intermediate_size": 8192,
  "max_position_embeddings": 131072,
  "mlp_bias": false,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 16,
  "num_key_value_heads": 8,
  "pad_token_id": 128004,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": {
    "factor": 32.0,
    "high_freq_factor": 4.0,
    "low_freq_factor": 1.0,
    "original_max_position_embeddings": 8192,
    "rope_type": "llama3"
  },
  "rope_theta": 500000.0,
  "tie_word_embeddings": true,
  "transformers_version": "4.57.1",
  "use_cache": true,
  "vocab_size": 128256
}

loading weights file llama_1b_nl2sh_finetuned/model.safetensors
Instantiating LlamaForCausalLM model under default dtype torch.bfloat16.
Generate config GenerationConfig {
  "bos_token_id": 128000,
  "eos_token_id": 128009,
  "pad_token_id": 128004
}

loading configuration file llama_1b_nl2sh_finetuned/generation_config.json
Generate config GenerationConfig {
  "bos_token_id": 128000,
  "do_sample": true,
  "eos_token_id": [
    128009,
    128001,
    128008,
    128009
  ],
  "pad_token_id": 128004,
  "temperature": 0.6,
  "top_p": 0.9
}

Could not locate the custom_generate/generate.py inside llama_1b_nl2sh_finetuned.
Generating predictions:   0%|          | 0/300 [00:00<?, ?it/s]- `temperature`: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
- `top_p`: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
If you're using a pretrained model, note that some of these attributes may be set through the model's `generation_config.json` file.
Generating predictions: 100%|██████████| 300/300 [01:44<00:00,  2.88it/s]
loading file vocab.json
loading file merges.txt
loading file tokenizer.json
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file chat_template.jinja

────────────────────────────────────────────────────────────────────────────────
📊 RESULTS: llama_1b_nl2sh_finetuned
────────────────────────────────────────────────────────────────────────────────
Correct: 33/300
Accuracy: 11.00%
────────────────────────────────────────────────────────────────────────────────

✅ Saved results to llama_1b_nl2sh_finetuned_benchmark.csv

================================================================================
Evaluating: qwen_0.5b_nl2sh_finetuned
================================================================================

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
loading configuration file qwen_0.5b_nl2sh_finetuned/config.json
Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 24,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pad_token_id": 151643,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "4.57.1",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

loading weights file qwen_0.5b_nl2sh_finetuned/model.safetensors
Instantiating Qwen2ForCausalLM model under default dtype torch.bfloat16.
Generate config GenerationConfig {
  "eos_token_id": 151645,
  "pad_token_id": 151643
}

loading configuration file qwen_0.5b_nl2sh_finetuned/generation_config.json
Generate config GenerationConfig {
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.05,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

Could not locate the custom_generate/generate.py inside qwen_0.5b_nl2sh_finetuned.
Generating predictions: 100%|██████████| 300/300 [02:15<00:00,  2.21it/s]

────────────────────────────────────────────────────────────────────────────────
📊 RESULTS: qwen_0.5b_nl2sh_finetuned
────────────────────────────────────────────────────────────────────────────────
Correct: 41/300
Accuracy: 13.67%
────────────────────────────────────────────────────────────────────────────────

✅ Saved results to qwen_0.5b_nl2sh_finetuned_benchmark.csv


🎉 BENCHMARKING COMPLETE!

In [12]:
from sentence_transformers import SentenceTransformer
import pandas as pd
from tqdm import tqdm

# Load embedding model
model = SentenceTransformer('all-MiniLM-L6-v2')

def semantic_similarity(pred, truth):
    """Calculate cosine similarity between two commands"""
    embeddings = model.encode([pred, truth])
    similarity = (embeddings[0] @ embeddings[1]) / (
        (embeddings[0] @ embeddings[0])**0.5 * (embeddings[1] @ embeddings[1])**0.5
    )
    return similarity

# Evaluate both models
for model_name in ['llama_1b_nl2sh_finetuned', 'qwen_0.5b_nl2sh_finetuned']:
    df = pd.read_csv(f'{model_name}_benchmark.csv')

    similarities = []
    correct_semantic = 0
    threshold = 0.8  # 80% similarity threshold

    print(f"\n{'='*80}")
    print(f"Semantic Evaluation: {model_name}")
    print(f"{'='*80}")

    for _, row in tqdm(df.iterrows(), total=len(df), desc="Computing similarities"):
        sim = semantic_similarity(row['prediction'], row['ground_truth'])
        similarities.append(sim)

        if sim >= threshold:
            correct_semantic += 1

    df['similarity'] = similarities
    df['semantic_correct'] = df['similarity'] >= threshold

    # Save updated results
    df.to_csv(f'{model_name}_semantic_eval.csv', index=False)

    # Print results
    exact_acc = (df['correct'].sum() / len(df)) * 100
    semantic_acc = (correct_semantic / len(df)) * 100
    avg_similarity = df['similarity'].mean()

    print(f"\nResults:")
    print(f"  Exact Match:    {exact_acc:.2f}%")
    print(f"  Semantic Match: {semantic_acc:.2f}% (threshold={threshold})")
    print(f"  Avg Similarity: {avg_similarity:.3f}")
    print(f"  Improvement:    +{semantic_acc - exact_acc:.2f}%")

print("\n✅ Semantic evaluation complete!")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 384,
  "initializer_range": 0.02,
  "intermediate_size": 1536,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 6,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.57.1",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

loading weights file model.safetensors from cache at /root/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/model.safetensors

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

loading file vocab.txt from cache at /root/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/vocab.txt
loading file tokenizer.json from cache at /root/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/tokenizer.json
loading file added_tokens.json from cache at None
loading file special_tokens_map.json from cache at /root/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/special_tokens_map.json
loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf/tokenizer_config.json
loading file chat_template.jinja from cache at None

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

================================================================================
Semantic Evaluation: llama_1b_nl2sh_finetuned
================================================================================

Computing similarities: 100%|██████████| 300/300 [00:02<00:00, 130.21it/s]

Results:
  Exact Match:    11.00%
  Semantic Match: 57.00% (threshold=0.8)
  Avg Similarity: 0.766
  Improvement:    +46.00%

================================================================================
Semantic Evaluation: qwen_0.5b_nl2sh_finetuned
================================================================================

Computing similarities: 100%|██████████| 300/300 [00:02<00:00, 133.82it/s]

Results:
  Exact Match:    13.67%
  Semantic Match: 60.33% (threshold=0.8)
  Avg Similarity: 0.776
  Improvement:    +46.67%

✅ Semantic evaluation complete!